name: meal_mesh_ios_driver
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.2.0
  get: ^4.7.3
  google_maps_flutter: ^2.14.2
  geolocator: ^14.0.2
  flutter_dotenv: ^6.0.0
  shared_ui:
    path: ../../packages/shared_ui
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
