// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy882FVHTE_c1UUkYGyJ27Ei0TJZrNnzY',
    appId: '1:407409670855:ios:e1167a1eb16c297dbb5ce2',
    messagingSenderId: '407409670855',
    projectId: 'meal-mesh-dbase',
    storageBucket: 'meal-mesh-dbase.firebasestorage.app',
    iosClientId: '407409670855-3j0dviun9823d2lf9tb7fti49usi9gjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealMeshIosDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpeehPra_SXGVjWP5pF_C3fRv8lLe7hpg',
    appId: '1:407409670855:web:c04edde1192384f2bb5ce2',
    messagingSenderId: '407409670855',
    projectId: 'meal-mesh-dbase',
    authDomain: 'meal-mesh-dbase.firebaseapp.com',
    storageBucket: 'meal-mesh-dbase.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpeehPra_SXGVjWP5pF_C3fRv8lLe7hpg',
    appId: '1:407409670855:web:1b987c2c373db770bb5ce2',
    messagingSenderId: '407409670855',
    projectId: 'meal-mesh-dbase',
    authDomain: 'meal-mesh-dbase.firebaseapp.com',
    storageBucket: 'meal-mesh-dbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy882FVHTE_c1UUkYGyJ27Ei0TJZrNnzY',
    appId: '1:407409670855:ios:e1167a1eb16c297dbb5ce2',
    messagingSenderId: '407409670855',
    projectId: 'meal-mesh-dbase',
    storageBucket: 'meal-mesh-dbase.firebasestorage.app',
    iosClientId: '407409670855-3j0dviun9823d2lf9tb7fti49usi9gjh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealMeshIosDriver',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhYv0bvr1Fw7LR_i88i6Ij2I9pRqw35E',
    appId: '1:407409670855:android:e82190c6d453f41bbb5ce2',
    messagingSenderId: '407409670855',
    projectId: 'meal-mesh-dbase',
    storageBucket: 'meal-mesh-dbase.firebasestorage.app',
  );

}